# Generated by Django 4.1.5 on 2023-01-22 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('include', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
